How to create numpy arrays

In [8]:
import numpy as np
l=[1,2,3]
print(np.array(l))

[1 2 3]


In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a=np.ones(10)
print(a)
print(a.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [13]:
b=np.ones(10,int)
print(b)

[1 1 1 1 1 1 1 1 1 1]


In [19]:
c=np.zeros((2,3),int)  #2D array
print(c)
print("--------------")
d=np.zeros((2,3,3),int)  #3D array
print(d)
print(d.shape)   #gives size of array

[[0 0 0]
 [0 0 0]]
--------------
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(2, 3, 3)


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(a)
print("-------------")
print(a[0])   #returns first row
print("-------------")
print(a[:,0]) #returns first column
print("-------------")
print(a[0:3,0])
print("-------------")
print(a[:,2:4])
print("-------------")
print(a[0:2,1:3])



[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
-------------
[1 2 3]
-------------
[1 4 1 4]
-------------
[1 4 1]
-------------
[[3]
 [6]
 [3]
 [6]]
-------------
[[2 3]
 [5 6]]


Numpy Operations

In [15]:
a=np.array([1,2,3])
b=np.array([5,6,7])

print(a+2) #adds 2 to the each element of the array
print(a+b) #adds elements of array at respective positions, but we cannot add arrays of different dimensions
print(a*2)
print(a*b)
print(a**2)
print(a**b)

[3 4 5]
[ 6  8 10]
[2 4 6]
[ 5 12 21]
[1 4 9]
[   1   64 2187]


In [17]:
print(a.mean())
print(a.sum())
print(b.mean())

2.0
6
6.0


Finding distance between two points in 3d space

In [23]:
import math as m
a=np.array([1,2,3])
b=np.array([5,6,7])
#let a and b are two points in three dimensional space
d=((a-b)**2).sum()
print(m.sqrt(d))

6.928203230275509


Finding the distance of a point from its mean

In [26]:
x=np.array([1,3,5,6])
d=((x-x.mean())**2).sum()
print(d)

14.75


Dot Product of two arrays

In [29]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[10,20],[30,40]])
a1.dot(a2)

array([[ 70, 100],
       [150, 220]])